name: icloudcn-for-linux
version: '0.11'
summary: iCloudCN for Linux
description: iCloudCN for Linux

grade: stable
confinement: strict
base: core20

layout:
  /usr/share/qt5:
    bind: $SNAP/usr/share/qt5

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]

  icloudcn-for-linux:
    after: [desktop-qt5]
    source: .
    plugin: make
    override-build: |
      set -eux
      qmake -set prefix $SNAPCRAFT_PART_INSTALL
      qmake
      snapcraftctl build
    build-packages:
      - qtdeclarative5-dev
    stage-packages:
      - qml-module-qt-labs-settings
      - qml-module-qt-labs-folderlistmodel
      - qml-module-qtquick2
      - qml-module-qtquick-controls
      - qml-module-qtquick-window2
      - qml-module-qtwebengine
      - qml-module-qtquick-dialogs

  dump:
    source: dump
    plugin: dump

apps:
  mail:
    command: bin/icloudcn-for-linux.launcher mail Mail
    plugs: &plugs
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - screen-inhibit-control
      - x11
    environment: &environment
      DISABLE_WAYLAND: 1
      QTWEBENGINE_DISABLE_SANDBOX: 1
  contacts:
    command: bin/icloudcn-for-linux.launcher contacts Contacts
    plugs: *plugs
    environment: *environment
  calendar:
    command: bin/icloudcn-for-linux.launcher calendar Calendar
    plugs: *plugs
    environment: *environment
  photos:
    command: bin/icloudcn-for-linux.launcher photos Photos
    plugs: *plugs
    environment: *environment
  drive:
    command: bin/icloudcn-for-linux.launcher iclouddrive Drive
    plugs: *plugs
    environment: *environment
  notes:
    command: bin/icloudcn-for-linux.launcher notes Notes
    plugs: *plugs
    environment: *environment
  reminders:
    command: bin/icloudcn-for-linux.launcher reminders Reminders
    plugs: *plugs
    environment: *environment
  pages:
    command: bin/icloudcn-for-linux.launcher pages Pages
    plugs: *plugs
    environment: *environment
  numbers:
    command: bin/icloudcn-for-linux.launcher numbers Numbers
    plugs: *plugs
    environment: *environment
  keynote:
    command: bin/icloudcn-for-linux.launcher keynote Keynote
    plugs: *plugs
    environment: *environment
  find-my-friends:
    command: bin/icloudcn-for-linux.launcher fmf Find-My-Friends
    plugs: *plugs
    environment: *environment
  find-my-iphone:
    command: bin/icloudcn-for-linux.launcher find Find-My-iPhone
    plugs: *plugs
    environment: *environment
